- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'delete a device member from a device group'
        fmgr_dvmdb_group_group:
            method: 'delete'
            url_params:
                adom: 'root'
                group: 'demo_group'
            params:
                - data:
                     - name: 'FGVM04TM19006963'
                       vdom: 'root'
