- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'get a firewall service'
        fmgr_pm_config_obj_firewall_service_custom:
            method: 'get'
            url_params:
                adom: "{{ adom }}"
            params:
                - filter:
                    - 'name'
                    - '=='
                    - 'firewall_demo_service0'
