- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'delete an ipv4 address'
        fmgr_pm_config_obj_firewall_address_address:
            method: 'delete'
            url_params:
                adom: 'root'
                address: 'firewall_ipv4_address_object0'
