- hosts: fortimanager01
  collections:
    - chillancezen.fortimanager
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'fetch all scripts'
        fmgr_dvmdb_script:
            method: 'get'
            url_params:
                adom: 'global'
            params:
                - fields:
                    - - 'name'
                      - 'type'
                      - 'desc'
                  sortings:
                    - name: -1
                    - type: 1
                    - content: 1
