- hosts: fortimanager01
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'update a script'
        ##async: 600
        ##poll: 0
        async: 7200
        poll: 0
        fmgr_dvmdb_script:
            url_params:
                adom: 'global'
            method: "set"
            params:
                - data:
                    - name: 'add_firewall_policy0'
                      desc: 'the demo script to set'
                      type: 'cli'
                      filter_ostype: 'unknown'
                      content: |
                                config firewall policy
                                    edit 1
                                        set name foopolicy
                                    next
                                end
 
    -   name: 'update a script'
        async: 7200
        poll: 0
        fmgr_dvmdb_script:
            url_params:
                adom: 'global'
            method: "set"
            params:
                - data:
                    - name: 'add_firewall_policy1'
                      desc: 'the demo script to set'
                      type: 'cli'
                      filter_ostype: 'unknown'
                      content: |
                                config firewall policy
                                    edit 1
                                        set name foopolicy
                                    next
                                end

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus0'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus1'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus2'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus3'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'

    -   name: 'Update a seurity profile anti-virus entry'
        async: 7200
        poll: 0
        fmgr_antivirus_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus4'
                      comment: 'A seurity profile anti virus entry updated by Ansible'
                      inspection-mode: 'flow-based'
