- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'update a seurity profile webfilter entry'
        fmgr_pm_config_obj_webfilter_profile:
            method: 'update'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_web_filter0'
                      comment: 'A seurity profile web filter entry updated by Ansible'
                      options:
                        - 'jscript'
                        - 'cookiefilter'
                      inspection-mode: 'flow-based'
