- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a seurity profile ssl_ssh entry'
        fmgr_pm_config_obj_firewall_ssl_ssh_profile:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_ssl_ssh0'
                      comment: 'A ssl&ssh security profile created by Ansible'
                      mapi-over-https: 'enable'
                      whitelist: 'disable'
