- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a seurity profile IPS sensor entry'
        fmgr_pm_config_obj_ips_sensor:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_ips_sensor0'
                      comment: 'A seurity profile ips sensor entry created by Ansible'
