- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a seurity profile WAF entry'
        fmgr_pm_config_obj_waf_profile:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_waf0'
                      comment: 'A seurity profile waf entry created by Ansible'
                      external: 'disable'
                      extended-log: 'enable'
