- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a device'
        fmgr_dvm_cmd_add_device:
            method: "exec"
            params:
                - data:
                    adom: 'root'
                    device:
                        adm_usr: 'admin'
                        adm_pass:
                            - 'admin'
                        desc: 'The Fortigate with IP 192.168.190.130'
                        ip: '192.168.190.130'
                        os_type: 'fos'
                        name: 'FGVM04TM19006963'
                        sn: 'FGVM04TM19006963'

