- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'get the device group'
        fmgr_dvmdb_group:
            method: 'get'
            url_params:
                adom: 'root'
            params:
                - sortings:
                    - name: 1
