- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add an ipv6 ippool'
        fmgr_pm_config_obj_firewall_ippool6:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'firewall_ipv6_ippool_object0'
                      comments: 'An ipv6 ippool object created by Ansible'
                      startip: '2001:0db8:85a3:0000:0000:8a2e:0370:1000'
                      endip: '2001:0db8:85a3:0000:0000:8a2e:0370:3333'
