- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    package: 'testpackage0'
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'Update an IPv4 firewall policy'
        fmgr_pm_config_pkg_pkg_firewall_policy:
            method: 'update'
            url_params:
                adom: "{{ adom }}"
                pkg: "{{ package }}"
            params:
                - data:
                    # note identifying a policy is via policy_id, not name
                    # To get the policy of the policy we just created just now,
                    # invoke firewall_policy_get.yml
                    - policyid: 5
                      name: 'firewall_ipv4_policy0'
                      srcintf: 'port1'
                      srcaddr: 'all'
                      dstintf: 'port1'
                      dstaddr: 'all'
                      action: 'accept'
                      service: 'ALL'
                      schedule: 'always'
                      comments: 'An IPv4 policy updated by ansible'
                      

