- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'delete a firewall vip object'
        fmgr_pm_config_obj_firewall_vip_vip:
            method: 'delete'
            url_params:
                adom: 'root'
                vip: 'firewall_vip_object0'
