- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a firewall package'
        fmgr_pm_pkg_adom_adom:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'testpackage0'
                      'obj ver': 1
                      type: 'pkg'

