- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'delete a seurity profile web-proxy entry'
        fmgr_pm_config_obj_web_proxy_profile_profile:
            method: 'delete'
            url_params:
                adom: 'root'
                profile: 'secprof_webproxy0'
