- hosts: fortimanager01
  connection: httpapi
  vars:
    adom: "root"
    ansible_httpapi_use_ssl: True
    ansible_httpapi_validate_certs: False
    ansible_httpapi_port: 443
  tasks:
    -   name: 'add a seurity profile anti-virus entry'
        fmgr_pm_config_obj_antivirus_profile:
            method: 'add'
            url_params:
                adom: 'root'
            params:
                - data:
                    - name: 'secprof_anti_virus0'
                      comment: 'A seurity profile anti virus entry created by Ansible'
                      inspection-mode: 'proxy'
